### ISSUE TITLE
Next Major Release

### ISSUE THREAD

**Issue by kderme** [input-output-hk/cardano-db-sync#1122]
Umbrella ticket for all remaining issue for the next major release 13.0.0. Some are necessary and some good to have.
- [x] HF integration https://github.com/input-output-hk/cardano-db-sync/issues/1081. Should be fixed here https://github.com/input-output-hk/cardano-db-sync/pull/1112
- [x] Performance Improvements https://github.com/input-output-hk/cardano-db-sync/issues/1120. Should be partially fixed in https://github.com/input-output-hk/cardano-db-sync/pull/1112. Remains to be investigated
- [x] Create changelog. Should first backport 12.0.2 changelog. 
- [x] Imrpove schema documentation https://github.com/input-output-hk/cardano-db-sync/issues/1118. Annotate all schema changes with `v13`.
- [ ] Good to have https://github.com/input-output-hk/cardano-db-sync/issues/942. ledger has added a new ada pots event, which should unblock this. Can be done on a minor release.
- [ ] Good to have https://github.com/input-output-hk/cardano-db-sync/issues/1115. This can be too easy to integrate or too hard. So it depends on if we're lucky. Can be done on a minor release.
- [x] Add light mode https://github.com/input-output-hk/cardano-db-sync/issues/905

**Comment by somereason** [comment]
Looking forward to next release! Current version has failed 3 time in last week.  due to performance issue

**Comment by erikd** [comment]
Performance of the next release is not likely to drastically improve compared to `12.0.x`. The following release hopefully will have some large performance improvements.

**Comment by somereason** [comment]
When will we have the next release? I'm expecting it every day.
